### PR TITLE
Merge many changes

### PR DESCRIPTION
**Pull request by mrhubbs**
The changes include:
- Some code reformatting
- Changes to make FlatKivy easier to use:
  - Created a FlatApp class (copying much of the code from flat_kivy/**init**.py
  - Split up the widgets to mirror the organization of the main Kivy code (e.g. from flat_kivy.uix.flatbutton import FlatButton)
  - Created a demo app (FlatKivy/demo.py)
- Created a "raised" style version of some widgets (taking the idea from Google's Material Design)
- Changed the default theme from the blue color
- Changed default ripple color
- Ripple color now behaves as an overlay (the ripple ellipse is drawn with some initial transparency)
- Implemented a FlatSlider
- If Scissor instructions are not available, instead uses Stencil instructions (so FlatKivy works with Kivy < 1.9.1)

Let me know how you want to sort things out between the two FlatSlider implementations.

### CODE REVIEW

**Comment by mrhubbs** [comment]
My implementation of the FlatSlider is located [here](https://github.com/mrhubbs/FlatKivy/blob/wdev/flat_kivy/uix/flatslider.py).

**Comment by mrhubbs** [comment]
Kovak,

I've incorporated all your updates and replaced my FlatSlider with yours.  This PR should be ready to merge.

**Comment by Kovak** [comment]
Great work! A truly beautiful revamp of this library, it is a lot closer to becoming a strong project thanks to your work.

I have been meaning to organize most of this for a while.

A couple things:

1. I had to revert your changes to ButtonBehavior because it was breaking ToggleButtons. I like the timeout you added in theory, but we need to make sure it works in all cases. Let's make a separate PR for just this feature.

2. The short hand <-FlatSlider> is a more elegant way to 'clear' the old graphics instructions. I was doing this in a few other places and did it there as well.

3. I went ahead and removed some of the commented out sections.

**Comment by mrhubbs** [comment]
Thank you!. :) I think this is a great project and enjoy working on it.

1: I've taken the liberty of opening #5 to address this.

2: Thanks for the tip.

4: Yes, I had the root-level **init** since I was using FlatKivy embedded in several other projects.  However, I had to modify sys.path to get FlatKivy to import anyways, so I don't see any reason to keep the root-level **init**.

**Pull request merged**
